<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="73d51c8f-5d3b-4d4a-ba04-c8b9a9041aa8" name="chadillac@CHADILLAC-PC 2012-02-23 11:32:40" runUser="chadillac-PC\chadillac" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="699621a8-4321-403e-843d-a1c2dba0af3c">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="chadillac_CHADILLAC-PC 2012-02-23 11_32_40">
      <DeploymentItem filename="C:\dev\pivotal-csharp-wrapper\PivotalTrackerAPIClient\bin\Debug\PivotalTrackerAPIClient.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2012-02-23T11:32:40.5185546-06:00" queuing="2012-02-23T11:32:41.4892578-06:00" start="2012-02-23T11:32:41.6191406-06:00" finish="2012-02-23T11:32:54.7314453-06:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="integration_authentication_get_by_username" storage="c:\dev\pivotal-csharp-wrapper\pivotaltrackerapiclient.tests\bin\debug\pivotaltrackerapiclient.tests.dll" id="2e466b0d-d78b-9341-073a-26e5e1537195">
      <Execution id="6e905e19-b6c9-47bc-823d-4d29070a730b" />
      <TestMethod codeBase="C:/dev/pivotal-csharp-wrapper/PivotalTrackerAPIClient.Tests/bin/Debug/PivotalTrackerAPIClient.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="PivotalTrackerAPIClient.Tests.Integration.Authentication, PivotalTrackerAPIClient.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="integration_authentication_get_by_username" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="2e466b0d-d78b-9341-073a-26e5e1537195" executionId="6e905e19-b6c9-47bc-823d-4d29070a730b" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="6e905e19-b6c9-47bc-823d-4d29070a730b" testId="2e466b0d-d78b-9341-073a-26e5e1537195" testName="integration_authentication_get_by_username" computerName="CHADILLAC-PC" duration="00:00:12.1987223" startTime="2012-02-23T11:32:41.7539062-06:00" endTime="2012-02-23T11:32:54.6210937-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="6e905e19-b6c9-47bc-823d-4d29070a730b">
      <Output>
        <ErrorInfo>
          <Message>Test method PivotalTrackerAPIClient.Tests.Integration.Authentication.integration_authentication_get_by_username threw exception: 
System.Net.WebException: The remote server returned an error: (401) Unauthorized.</Message>
          <StackTrace>    at System.Net.HttpWebRequest.GetResponse()
   at PivotalTrackerAPIClient.Authentication.RetrieveToken(String username, String password) in C:\dev\pivotal-csharp-wrapper\PivotalTrackerAPIClient\Authentication.cs:line 26
   at PivotalTrackerAPIClient.Tests.Integration.Authentication.integration_authentication_get_by_username() in C:\dev\pivotal-csharp-wrapper\PivotalTrackerAPIClient.Tests\Integration\Authentication.cs:line 14
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>